### ISSUE TITLE
[CI] standalone job is not running tests

### ISSUE THREAD

**Issue by mmurooka** [isri-aist/NMPC#4]
https://github.com/isri-aist/NMPC/actions/runs/3666505498/jobs/6198250807#step:5:925

The catkin build job runs the tests.
https://github.com/isri-aist/NMPC/actions/runs/3666499431/jobs/6198239246#step:8:1766

**Comment by gergondet** [comment]
Because of the meta-project approach the standalone build takes, the tests are run as part of the build step. The output is a little scrambled because the tests are allowed to run while the next project is building but if you search for "tests passed" you should see the outputs of the tests of each project). If a test fail, the build will fail as well.

However I see how this can be confusing so I have added standalone tests target for each project

**Comment by mmurooka** [comment]
Oh, thank you for the explanation. The tests were indeed running in the build steps.
